version: "3.9"
services:
  api-server:
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
      - logvolume01:/var/log
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
volumes:
  logvolume01: {}