version: "3.9"
services:
  api-server:
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/code
      - logvolume01:/var/log
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-dev
    ports:
      - "27017:27017"
    command: mongod
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
volumes:
  logvolume01: {}